Bottstrapping, app updates, etc.
aliaksandrkazlou/texts_comparison pull request #2
Opened 2022-07-04 22:35 UTC by mickolka

2022-07-05 09:37 UTC, mickolka commented
Bootstrapping still needs some thought:

- What should be the default `k`?
- No-bootstrapping per-sentence metrics are to the right of the CI, which is sort of the point, I guess? 🤔 
- When sampling with replacement, current definition of lexical diversity metric becomes meaningless

2022-07-05 17:39 UTC, aliaksandrkazlou requested changes

2022-07-05 17:39 UTC, aliaksandrkazlou commented on functions.py
> +        k = len(sentences)
I believe that's the only way to bootstrap. Then bootstrapped CI has a nice property of being a measure of uncertainty to an estimate.

2022-07-05 17:39 UTC, aliaksandrkazlou commented on functions.py
>          "Lexical diversity": lex_diversity,
Yeah, it's meaningless when bootstrapped. I also had concerns regarding its sensitivity in general. I suggest getting rid of it.

2022-07-06 19:52 UTC, aliaksandrkazlou approved these changes

2022-07-06 19:52 UTC, merged